"""criar coluna descricao

Revision ID: 163f515fd45a
Revises: 1ceebbf6dcc5
Create Date: 2026-04-27 14:12:45.826978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163f515fd45a'
down_revision: Union[str, Sequence[str], None] = '1ceebbf6dcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('descricao', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'descricao')
    # ### end Alembic commands ###
